List<Map<String, dynamic>> iconsData = [
  {
    'caseName': 'Love',
    'information':
        '"Love-related cases that end up in court can be emotionally challenging and complex. Here are some common scenarios and general guidelines on how to handle them:\n\nDivorce and Separation: Divorce or separation cases are among the most common types of love-related legal disputes. When a marriage or long-term relationship breaks down irretrievably, couples may decide to pursue a legal dissolution. This involves issues like asset division, child custody, child support, alimony, and more.\nHow to act: In these situations, its essential to maintain open communication with your partner and, if possible, consider alternative dispute resolution methods like mediation to reach a fair settlement. If litigation becomes necessary, seek legal counsel to protect your rights and interests.\n\nDomestic Violence: In abusive relationships, victims may seek protection orders against their abusers to ensure their safety and the safety of their children.\nHow to act: If you are a victim of domestic violence, prioritize your safety and seek help from local law enforcement or domestic violence support organizations. They can assist you in obtaining a restraining order or protective order. Reach out to friends, family, or support groups to create a safety plan.\n\nChild Custody and Visitation Disputes: When parents separate, determining child custody and visitation rights can lead to contentious legal battles.\nHow to act: Focus on the well-being of the children involved and try to work out a parenting plan with the other parent that promotes the childs best interests. If an agreement cannot be reached, consult with an experienced family lawyer to navigate the legal process.\n\nProperty Disputes: Unmarried couples who cohabitate or share property may face legal battles over property ownership and asset division if the relationship ends.\nHow to act: Its advisable to establish clear agreements about property ownership and financial contributions at the beginning of the relationship. If a dispute arises, consult a property lawyer to understand your rights and options.\n\nBreach of Promise: Although less common in modern times, breach of promise cases can occur when one party alleges that their partner reneged on a promise to marry them.\nHow to act: Proving a breach of promise can be challenging legally. Seeking legal advice will help you understand if you have a valid case or if its better to pursue other legal avenues.\n\nIn any love-related legal case, it is crucial to approach the situation calmly and objectively. Emotions can run high in these situations, but its essential to be respectful and considerate throughout the process. Seek professional legal advice to understand your rights and responsibilities and explore peaceful resolutions whenever possible. Remember, each case is unique, so tailor your approach based on your specific circumstances."'
  },
  {
    'caseName': 'Alcohol',
    'information':
        'Common cases related to alcohol that end up in court include:\n\nDriving Under the Influence (DUI) or Driving While Intoxicated (DWI): This occurs when a person operates a vehicle while under the influence of alcohol or drugs. DUI/DWI cases can lead to legal consequences, such as fines, license suspension, probation, or even jail time.\nHow to act: Avoid driving if you have been drinking. Use alternative transportation methods like a designated driver, public transportation, or rideshare services. If you are facing a DUI/DWI charge, seek legal representation to navigate the legal process and explore potential defenses.\n\nPublic Intoxication: This refers to being visibly intoxicated and disruptive in public places, which can lead to arrest and fines.\nHow to act: Drink responsibly and be aware of your alcohol consumption in public spaces. If you or someone you know is intoxicated in public, try to find a safe place to rest or sober up. Avoid engaging in disruptive behavior.\n\nUnderage Drinking: Minors caught consuming alcohol or possessing fake IDs to buy alcohol may face legal consequences.\nHow to act: If you are underage, refrain from consuming alcohol. Its essential to be aware of the legal drinking age in your area and the potential consequences of underage drinking. Parents should educate their children about the risks of alcohol use and enforce age-appropriate boundaries.\n\nAlcohol-Related Assault or Violence: Alcohol can contribute to aggressive behavior, leading to alcohol-related assaults or violence, which may result in criminal charges.\nHow to act: Consume alcohol responsibly and know your limits. Avoid confrontations or arguments when under the influence. Seek help if you have anger or violence issues related to alcohol use.\n\nAlcohol-Related Property Damage: Intoxicated individuals may cause property damage, leading to potential legal disputes.\nHow to act: Avoid excessive drinking to prevent impaired judgment that could result in property damage. Take responsibility for any accidental damage caused while intoxicated and try to make amends if possible.'
  },
  {
    'caseName': 'Cars',
    'information':
        'Common cases related to cars that end up in court include:\n\nTraffic Violations: These are common cases involving speeding, running red lights, improper lane changes, driving without a valid license, or other infractions.\nHow to act: Obey traffic laws and regulations to avoid violations. If you receive a traffic ticket, you may contest it in court or pay the fine as required by law.\n\nCar Accidents: Cases may arise from car accidents caused by negligence, distracted driving, drunk driving, or other factors.\nHow to act: Drive attentively, avoid distractions, and never drink and drive. If youre involved in an accident, check for injuries and seek medical attention if necessary. Report the incident to the police, exchange insurance information, and cooperate with authorities. Consult with an attorney if there are disputes over fault or insurance claims.\n\nStolen Vehicles: When a car is stolen, it can lead to insurance claims and, in some cases, legal proceedings if the vehicle is involved in criminal activities.\nHow to act: Take preventive measures to protect your car, such as using an anti-theft device and parking in well-lit areas. Report the theft to the police and your insurance company promptly.\n\nLemon Law Cases: These cases involve cars that have recurring defects or problems despite multiple repair attempts.\nHow to act: Familiarize yourself with lemon laws in your region to understand your rights as a consumer. Keep records of repairs and communication with the dealership. If the problems persist, consult with a lawyer to explore potential remedies.\n\nPersonal Injury Claims: Car accidents can result in personal injury claims when individuals seek compensation for injuries sustained in a crash.\nHow to act: If youre injured in a car accident, seek medical attention immediately. Gather evidence from the scene, take pictures, and collect contact information from witnesses. Consult with a personal injury attorney to understand your rights and options for seeking compensation.'
  },
  {
    'caseName': 'Disability',
    'information':
        'Cases related to disability that may end up in court can encompass a range of legal issues. Here are some common scenarios and general guidance on how to address them:\n\nDisability Discrimination: This involves cases where individuals with disabilities face discrimination in employment, housing, education, or public accommodations.\nHow to act: Familiarize yourself with disability rights laws, such as the Americans with Disabilities Act (ADA) in the United States or similar legislation in other countries. If you believe you have experienced discrimination, document the incidents and seek legal counsel to understand your rights and potential recourse.\n\nSocial Security Disability Benefits: Disputes may arise when individuals are denied or have their disability benefits terminated.\nHow to act: If you believe you are eligible for Social Security Disability benefits, consult with an experienced disability attorney to help with the application process and any appeals necessary.\n\nAccessibility Issues: Disabled individuals may encounter barriers to access in public spaces, such as lack of wheelchair ramps or accommodations.\nHow to act: Report accessibility issues to the relevant authorities or organizations responsible for compliance with disability access laws. Document the problems and follow up on any actions taken to rectify the situation.\n\nGuardianship and Conservatorship: In some cases, disabled individuals may require guardians or conservators to handle their financial or personal affairs.\nHow to act: Seek legal advice on the process of establishing guardianship or conservatorship, ensuring that the disabled persons rights and wishes are respected.\n\nDisability Insurance Claims: Disputes can arise when insurance companies deny disability claims or terminate benefits.\nHow to act: Review your insurance policy carefully and gather all necessary documentation to support your claim. If your claim is denied, consider consulting with an attorney who specializes in disability insurance law to explore your options.'
  },
  {
    'caseName': 'Government',
    'information':
        'Cases related to the government that may end up in court can be diverse and cover various legal issues. Here are some common scenarios and general guidelines on how to approach them:\n\nAdministrative Law Cases: These cases involve disputes between individuals or businesses and government agencies over administrative decisions, permits, licenses, or regulatory matters.\nHow to act: If you have concerns about a government decision or need to challenge an agencys ruling, consult with an attorney familiar with administrative law to understand your options and the relevant procedures.\n\nCivil Rights Violations: Cases may arise when government officials or entities violate individuals constitutional rights, such as freedom of speech, religion, or protection from unreasonable searches.\nHow to act: If you believe your civil rights have been violated by the government, consult with a civil rights attorney to assess your situation and determine if legal action is appropriate.\n\nEminent Domain and Land Use Cases: Governments may exercise eminent domain to acquire private property for public use, leading to disputes over compensation or the legality of the taking.\nHow to act: Seek legal representation if your property is subject to eminent domain, to ensure that you receive fair compensation and that your rights are protected.\n\nFreedom of Information Act (FOIA) Requests: Disputes can arise when individuals or organizations seek access to government records through FOIA requests, and the government denies or redacts information.\nHow to act: If you encounter challenges with your FOIA request, consider seeking legal advice to understand your rights and explore options for accessing the requested information.\n\nWhistleblower Cases: Employees or individuals who report government misconduct or fraud may face retaliation or wrongful termination.\nHow to act: If youre a whistleblower facing adverse actions, seek legal counsel to protect your rights and consider filing a complaint under relevant whistleblower protection laws.'
  },
  {
    'caseName': 'Money',
    'information':
        '\nCases related to money that may end up in court can involve various financial disputes and legal issues. Here are some common scenarios and general guidelines on how to approach them:\n\nContract Disputes: Cases may arise when parties involved in a contract disagree over terms, payment, or performance.\nHow to act: Ensure that all contracts are well-drafted and clearly outline the rights and obligations of each party. If a dispute occurs, seek legal advice to understand your rights and explore options for resolution, such as negotiation, mediation, or litigation.\n\nDebt Collection: Creditors may pursue legal action to collect unpaid debts from individuals or businesses.\nHow to act: If you are facing debt collection proceedings, its essential to understand your rights under debt collection laws. Consult with an attorney to explore options like debt negotiation, settlement, or bankruptcy, depending on your financial situation.\n\nFraud and Scams: Cases involving financial fraud or scams, such as identity theft or investment fraud, may require legal action to recover losses or seek justice.\nHow to act: If you are a victim of fraud, report the incident to law enforcement and relevant authorities. Consult with an attorney to understand your legal options for recovering losses and holding the perpetrators accountable.\n\nEmployment Disputes: These cases involve issues like unpaid wages, wrongful termination, or workplace discrimination.\nHow to act: Document all relevant employment-related matters and seek legal counsel if you believe your rights as an employee have been violated. Employment laws vary by jurisdiction, so understanding local regulations is crucial.\n\nEstate and Probate Disputes: Legal conflicts can occur over the distribution of assets and inheritances in wills or during the probate process.\nHow to act: If you are involved in an estate or probate dispute, consult with an estate planning attorney to understand your rights and explore resolution options, such as mediation or litigation.\n\n'
  },
  {
    'caseName': 'Identity',
    'information':
        "Cases related to identity that may end up in court can involve various forms of identity theft, fraud, or misuse of personal information. Here are some common scenarios and general guidelines on how to approach them:\n\nIdentity Theft: This occurs when someone steals another person's personal information, such as Social Security numbers, credit card details, or passwords, to commit fraud or other illegal activities.\nHow to act: If you suspect you are a victim of identity theft, report it to the police and relevant authorities immediately. Notify your bank, credit card companies, and other financial institutions to secure your accounts. Consider placing a fraud alert or credit freeze with credit bureaus to prevent further harm.\n\nOnline Identity Fraud: Cases may involve individuals creating fake profiles or impersonating others online for malicious purposes.\nHow to act: Report online identity fraud to the website or social media platform where it occurs. Save evidence, such as screenshots or links to the fake profile, to support your case. In severe situations, consult with an attorney to explore legal action against the perpetrator.\n\nIdentity Misuse in Employment or Immigration: Cases can arise when someone uses false identification or misrepresents themselves during the hiring process or immigration proceedings.\nHow to act: If you suspect identity misuse in employment or immigration matters, report it to the relevant authorities, such as the human resources department or immigration agencies. Seek legal advice to understand your rights and potential recourse.\n\nIdentity Fraud in Financial Transactions: Disputes may occur when someone uses another person's identity to open bank accounts, take out loans, or make unauthorized financial transactions.\nHow to act: Contact your bank or financial institution immediately to report the fraudulent activity. File a police report and provide any evidence to support your claim. Work with the financial institution and potentially consult with an attorney to resolve the matter and restore your financial standing.\n\nIdentity Misuse in Criminal Activity: In some cases, individuals may use stolen identities to commit crimes, leading to legal consequences for the victim.\nHow to act: If your identity has been used in criminal activity, report it to law enforcement and cooperate fully in the investigation. Retain legal counsel to protect your rights and ensure you are not wrongfully held responsible for the crimes."
  },
  {
    'caseName': 'Tourism',
    'information':
        'Cases related to tourism that may end up in court can involve various legal issues concerning travelers, tour operators, and tourism-related businesses. Here are some common scenarios and general guidelines on how to approach them:\n\nTravel Disputes: Cases may arise when travelers encounter issues with flight cancellations, delays, lost luggage, or overbooking.\nHow to act: Keep records of your travel arrangements and any issues encountered during your trip. Communicate with the travel provider (airline, hotel, etc.) to resolve the problem. If the matter remains unresolved, consider filing a complaint with relevant consumer protection agencies or consulting with an attorney specializing in travel law.\n\nTour Operator Liability: Tour operators may face legal action if they fail to deliver promised services or if travelers suffer injuries during a tour or excursion.\nHow to act: Understand the terms and conditions of the tour package or excursion before booking. If an incident occurs during the trip, report it to the tour operator immediately and seek medical attention if needed. Document the incident and consult with a personal injury lawyer if you believe the tour operator was negligent.\n\nTravel Insurance Claims: Disputes may arise when travelers encounter difficulties with their travel insurance claims, such as denied coverage or delayed reimbursement.\nHow to act: Review your travel insurance policy carefully to understand coverage and exclusions. Keep all relevant documentation, including receipts and medical records, to support your claim. If your claim is denied or delayed, communicate with the insurance company, and consider seeking legal advice if necessary.\n\nTourism Business Regulations: Tourism-related businesses, such as hotels, restaurants, or tour agencies, may face legal challenges related to licensing, zoning, or compliance with local regulations.\nHow to act: Ensure your tourism business adheres to all relevant laws and regulations. Seek legal counsel to navigate any legal issues related to licensing, zoning, or other compliance matters.\n\nTourist Safety: In cases of accidents, injuries, or crimes involving tourists, legal action may be taken against individuals or entities responsible.\nHow to act: If you are a victim of an accident or crime while traveling, report it to local authorities and seek medical assistance if needed. Cooperate with law enforcement in the investigation. If necessary, consult with a local attorney familiar with tourism-related legal issues."'
  },
];
